### ISSUE TITLE
Error: 'CalculateMiracle' is not an exported object from 'namespace:Miracle' II

### ISSUE THREAD

**Issue by csmatyi** [tolgaturan-github/Miracle#2]
Hello all,
I am trying to run this command:

Miracle::CalculateMiracle(TCGA_BLCA_EDASeq_norm,"ens")
but get this error:
Error: 'CalculateMiracle' is not an exported object from 'namespace:Miracle'

As far as I can tell, I am running all the commands in the vignette properly. What could be going wrong?
Thanks,

**Comment by tolgaturan-github** [comment]
Hello Matthew, Thanks for reaching out and for your question. The function
name is Calculate_Miracle(), with an underscore. It should work this way.
Please let us know any other questions.
Tolga

**Comment by csmatyi** [comment]
Thanks! That helps
