### ISSUE TITLE
Calculate_Miracle not running

### ISSUE THREAD

**Issue by csmatyi** [tolgaturan-github/Miracle#3]
Hello, I have a matrix called patient_gene_matrix, with 199 genes, 5 patients:
> dim(patient_gene_matrix)
[1] 199   5

This is what it looks like:

                TCGA-OR-A5J1 TCGA-OR-A5J2 TCGA-OR-A5J3 TCGA-OR-A5J5 TCGA-OR-A5J6
ENSG00000165029  0.057072178  0.214234112  0.177608967  0.055255150  0.157534097
ENSG00000144476  0.021714269  0.074201703  0.108676679  0.019848316  0.002813977
ENSG00000109321  0.001057277  0.004614335  0.001566026  0.002730078  0.003695236
ENSG00000162772  0.220578334  0.141337937  0.068899439  0.012654294  0.046715580
ENSG00000070961  0.088626124  0.135986421  0.138036897  0.047565345  0.001355592
ENSG00000086062  0.044134502  0.161024747  0.191889841  0.111498539  0.133194505

The values may be negative, because they are z-scores of expression values.

I get these errors:

1.
The number of elements of the gene set is less than the minimum allowed.
Error in yaGST1_df1$Pos/yaGST1_df1$Neg : 
  non-numeric argument to binary operator

2.
 [6] "IDsENSG00000172116 not present in the expression matrix for the geneset ICR"
[50] "IDsENSG00000244649 not present in the expression matrix for the geneset Pos"
 [1] "IDsENSG00000029559 not present in the expression matrix for the geneset Neg"

What is wring here?
Thanks!

**Comment by tolgaturan-github** [comment]
Hi Matt,

Miracle is designed to work with genome-wide gene expression datasets. It works best with ~60K Ensembl gene model. For this reason, 199 features-matrix  is too small. The least number of features we tried successfully was Affymetrix U133A microarray platform. Also if the matrix has a lot of NAs it will error out similarly, even if there are 20K features in the matrix.

Best,
Tolga
